AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >

Globals:
  Function:
    Timeout: 10

Resources:
  ServerlessGetCostApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
      Auth:
        UsagePlan:
          CreateUsagePlan: PER_API
          UsagePlanName: GetCostAuthorization
  
  ServerlessUploadApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
      Auth:
        UsagePlan:
          CreateUsagePlan: PER_API
          UsagePlanName: UploadAuthorization

  GetCostFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: merchants/
      Handler: getCost.lambdaHandler
      Runtime: nodejs14.x
      Policies:
        - S3ReadPolicy:
            BucketName: "merchants-app-bucket-123"
      Architectures:
        - x86_64
      Environment:
        Variables:
          BucketName: "merchants-app-bucket-123"
      Events:
        GetCostEvent:
          Type: Api
          Properties:
            Path: /getcost
            Method: POST
            RestApiId:
              Ref: ServerlessGetCostApi
            Auth:
              ApiKeyRequired: true

  UploadToS3Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: merchants/
      Handler: upload.lambdaHandler
      Runtime: nodejs14.x
      Policies:
        - AmazonS3FullAccess
      Architectures:
        - x86_64
      Environment:
        Variables:
          BucketName: "merchants-app-bucket-123"
      Events:
        UploadEvent:
          Type: Api
          Properties:
            Path: /upload
            Method: post
            RestApiId: !Ref ServerlessUploadApi
            Auth:
              ApiKeyRequired: true
