AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >

Globals:
  Function:
    Timeout: 10

Resources:
  ServerlessGetCostApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        ApiKeyRequired: true
        UsagePlan:
          CreateUsagePlan: PER_API
          UsagePlanName: GetCostAuthorization
  
  ServerlessUploadApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        ApiKeyRequired: true
        UsagePlan:
          CreateUsagePlan: PER_API
          UsagePlanName: UploadAuthorization

  MerchantsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: merchants/
      Handler: getCost.lambdaHandler
      Runtime: nodejs14.x
      Policies:
        - S3ReadPolicy:
            BucketName: "example-test-for-sam"
      Architectures:
        - x86_64
      Events:
        GetCostEvent:
          Type: Api
          Properties:
            Path: /getcost
            Method: POST
            RequestParameters:
              - method.request.header.Authorization:
                  Required: true
                  Caching: true
            RestApiId:
              Ref: ServerlessGetCostApi

  UploadToS3Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: merchants/
      Handler: upload.lambdaHandler
      Runtime: nodejs14.x
      Policies:
        - S3FullAccessPolicy:
            BucketName: "example-test-for-sam"
      Architectures:
        - x86_64
      Events:
        UploadEvent:
          Type: Api
          Properties:
            Path: /upload
            Method: post
            RequestParameters:
              - method.request.header.Authorization:
                  Required: true
                  Caching: true
            RestApiId: !Ref ServerlessUploadApi
